name: ARM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    name: ECL (${{ matrix.cffi }}) with duckdb ${{ matrix.duckdb }} on ARM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ecl: [21.2.1]
        cffi: [static]
        duckdb: [0.8.0]
    env:
      DUCKDB_VERSION: ${{ matrix.duckdb }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies & run tests
        uses: pguyot/arm-runner-action@v2
        with:
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          image_additional_mb: 1024
          commands: |
            apt-get --yes install git build-essential aria2 unzip clang m4 libgc-dev libffi-dev lld ecl
            # git clone --depth 1 --branch ${{ matrix.ecl }} https://gitlab.com/embeddable-common-lisp/ecl.git
            # cd ecl
            # ./configure CC=clang LD=ld.lld --enable-threads --with-defsystem && make -j2 && make install
            # cd ../
            wget https://beta.quicklisp.org/quicklisp.lisp
            ecl --load quicklisp.lisp --eval '(progn (quicklisp-quickstart:install) (quit))'
            ecl --load ~/quicklisp/setup.lisp --eval '(progn (ql:quickload :periods) (ql:quickload :local-time) (load #P"debug.lisp") (quit))'
