name: BSD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.org'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    name: ${{ matrix.lisp }} (${{ matrix.cffi }}) on ${{ matrix.os }}
    runs-on: macos-latest
    strategy:
      matrix:
        os: [FreeBSD]
        lisp: [ecl/21.2.1]
        cffi: [default, static]
        exclude:
          - lisp: sbcl-bin
            cffi: static
          - lisp: ccl-bin/1.12.1
            cffi: static

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies & run tests
        uses: vmactions/freebsd-vm@v0.3.0
        with:
          usesh: true
          sync: rsync
          copyback: false
          prepare: |
            sed 's/quarterly/latest/' /etc/pkg/FreeBSD.conf > /tmp/FreeBSD.conf && mv /tmp/FreeBSD.conf /etc/pkg/
            pkg install -y duckdb bash roswell autoconf texinfo perl5 gmake gcc libffi
            ln -s /usr/local/bin/gmake /bin/make
            ln -s /usr/local/bin/bash /usr/local/bin/sh # ugh
            export PATH=/usr/local/bin/:$PATH
            ros install ${{ matrix.lisp }}
            ros install neil-lindquist/ci-utils
            ros use ${{ matrix.lisp }}
            ros run --eval '(progn (ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil) (uiop:quit))'
          run: |
            ln -s $(pwd) ~/.roswell/local-projects/cl-duckdb
            if [ ${{ matrix.cffi }} = 'static' ]; then export CL_DUCKDB_USE_SFFI=t; fi
            ~/.roswell/bin/run-fiveam -e t -l duckdb/test :duckdb
