name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }} with duckdb ${{ matrix.duckdb }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin, ecl]
        os: [ubuntu-latest, windows-latest, macos-latest]
        duckdb: [0.5.1]
        exclude:
          - os: windows-latest
            lisp: ccl-bin
          - os: windows-latest
            lisp: ecl
    env:
      LISP: ${{ matrix.lisp }}
      DUCKDB_VERSION: ${{ matrix.duckdb }}
    steps:
      - uses: actions/checkout@v2
          
      - name: Install DuckDB (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          aria2c "https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-linux-amd64.zip"
          unzip libduckdb-linux-amd64.zip -d .

      - name: Install DuckDB (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          aria2c "https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-osx-universal.zip"
          7z x libduckdb-osx-universal.zip

      - name: Install DuckDB (Windows)
        if: runner.os == 'Windows'
        run: |
          aria2c "https://github.com/duckdb/duckdb/releases/download/v$env:DUCKDB_VERSION/libduckdb-windows-amd64.zip"
          7z x libduckdb-windows-amd64.zip

      - name: Setup Lisp (Non-Windows)
        uses: 40ants/setup-lisp@v2
        if: runner.os != 'Windows'
          
      - name: Setup sbcl-bin/2.2.6 (Windows)
        uses: 40ants/setup-lisp@v2
        if: runner.os == 'Windows'
        env:
          LISP: sbcl-bin/2.2.6
          
      - name: Run tests (Non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          export DYLD_LIBRARY_PATH=./
          export LD_LIBRARY_PATH=./
          ros install neil-lindquist/ci-utils
          run-fiveam -e t -l duckdb/test :duckdb

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/:./
          export LIBRARY_PATH=$LIBRARY_PATH:/usr/lib/:./
          pacman --noconfirm -S libffi-devel
          ros install neil-lindquist/ci-utils
          run-fiveam -e t -l duckdb/test :duckdb
