name: Nightly

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.org'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  test:
    name: ${{ matrix.lisp }} (${{ matrix.cffi }}) on ${{ matrix.os }} with duckdb nightly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        lisp: [sbcl-bin, ccl-bin/1.13, ecl/24.5.10]
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        quicklisp-dist:
          - ultralisp
        cffi: [default, static]
        exclude:
          - lisp: sbcl-bin
            cffi: static
          - lisp: ccl-bin/1.13
            cffi: static
          - os: windows-latest
            lisp: ccl-bin/1.13
          - os: windows-latest
            lisp: ecl/24.5.10
          - os: macos-14
            lisp: ccl-bin/1.13
    env:
      LISP: ${{ matrix.lisp }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Lisp
        uses: 40ants/setup-lisp@v4
        with:
          cache: true

      - name: Install DuckDB (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          aria2c "https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip"
          unzip duckdb-binaries-linux.zip -d .
          unzip libduckdb-linux-amd64.zip -d .

      - name: Install DuckDB (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          aria2c "https://artifacts.duckdb.org/latest/duckdb-binaries-osx.zip"
          7z x duckdb-binaries-osx.zip
          7z x libduckdb-osx-universal.zip

      - name: Install DuckDB (Windows)
        if: runner.os == 'Windows'
        run: |
          aria2c "https://artifacts.duckdb.org/latest/duckdb-binaries-windows.zip"
          7z x duckdb-binaries-windows.zip
          7z x libduckdb-windows-amd64.zip

      - name: Run tests (Non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          export DYLD_LIBRARY_PATH=./
          export LD_LIBRARY_PATH=./
          if [ ${{ matrix.cffi }} = 'static' ]; then export CL_DUCKDB_USE_SFFI=t; fi
          export CL_DUCKDB_LIBRARY_PATH="${{ github.workspace }}"
          if [ ${{ matrix.os }} = 'macos-latest' ]; then sudo cp ./libduckdb.dylib /usr/local/lib/; fi
          ros install neil-lindquist/ci-utils
          asdf-register-project
          ros --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' --eval '(ql:quickload :duckdb)' --eval '(duckdb:with-transient-connection (format t "~%DuckDB source_id: ~A~%" (duckdb:get-result (duckdb:q "PRAGMA version") (quote source-id) 0)))' --eval '(uiop:quit)'
          run-fiveam -e t -l duckdb/test :duckdb

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          if [ ${{ matrix.cffi }} = 'static' ]; then export CL_DUCKDB_USE_SFFI=t; fi
          export CL_DUCKDB_LIBRARY_PATH="${{ github.workspace }}"
          pacman --noconfirm -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-libffi
          ros --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' --eval '(ql:quickload :cffi-grovel)' --eval "(progn (setf cffi-grovel::*cc-flags* (append (list \"-I`cygpath -w /mingw64/include`\") cffi-grovel::*cc-flags*)) (ql:quickload :cffi-libffi))" --eval '(ql:quickload :duckdb)' --eval '(duckdb:with-transient-connection (format t "~%DuckDB source_id: ~A~%" (duckdb:get-result (duckdb:q "PRAGMA version") (quote source-id) 0)))' --eval '(uiop:quit)'
          ros --eval '(ql:quickload :cffi-grovel)' --eval "(progn (setf cffi-grovel::*cc-flags* (append (list \"-I`cygpath -w /mingw64/include`\") cffi-grovel::*cc-flags*)) (ql:quickload :cffi-libffi))" --eval "(progn (ql:quickload :duckdb/test) (uiop:quit (if (uiop:symbol-call :fiveam '#:run! :duckdb) 0 1)))"
